### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by bcomnes** [chapmanu/fragmentions#13]
Would be great to get this on npm.  I would be willing to be a collaborator and get this published.

**Comment by jonathantneal** [comment]
I may not be able to get to this right away, but I can handle it.

**Comment by bcomnes** [comment]
I'll PR a `package.json` in preparation.

**Comment by jonathantneal** [comment]
Heh, we kinda let this get away.

**Comment by bcomnes** [comment]
Just cleaning up old issues that I created.  Feel free to reopen if its of any value still.

**Comment by jonathantneal** [comment]
I’ll ask how many folks are using this on Twitter. I saw it was used the other week @ https://resilientwebdesign.com/ ([cite](https://twitter.com/kartik_prabhu/status/808814030890659840)). Plus, I’m not sure I knew how to package things when we started this issue.

**Comment by bcomnes** [comment]
Its a cool script for sure!  I think npming would still be a good idea.  I just don't have the bandwidth right now to track it, and Im not currently using it.  But I still want to eventually.

**Comment by malcolmocean** [comment]
I have it on my site, [malcolmocean.com](https://malcolmocean.com). I sometimes find this helpful for linking people to a specific spot in my blog post.
